package tn.esprit.workshop.ai.agent;

/**
 * Read-only intents for the agent school assistant (V1 whitelist).
 */
public enum AgentChatIntentType {

    COUNT_MAITRESSES,
    COUNT_ENFANTS,
    COUNT_ENFANTS_ACCEPTED_CANDIDATURES,
    COUNT_BUS,
    COUNT_TRAJETS,
    COUNT_PENDING_ENFANT_CANDIDATURES,
    COUNT_PENDING_CHAUFFEUR_CANDIDATURES,
    COUNT_BUSES_WITHOUT_MAITRESSE,
    COUNT_TRAJETS_WITHOUT_BUS,
    COUNT_BUSES_WITH_CHAUFFEUR,
    COUNT_BUSES_WITHOUT_CHAUFFEUR,

    COUNT_CHAUFFEURS,
    COUNT_CHAUFFEURS_ASSIGNED,
    COUNT_CHAUFFEURS_UNASSIGNED,

    COUNT_ENFANTS_TRANSPORTED,
    COUNT_ENFANTS_ON_BOARD,
    COUNT_ENFANTS_OFF_BOARD,

    LIST_BUSES_ASSIGNED_CHAUFFEUR,
    LIST_BUSES_UNASSIGNED_CHAUFFEUR,

    LIST_CHAUFFEURS,
    LIST_CHAUFFEURS_ASSIGNED,
    LIST_CHAUFFEURS_UNASSIGNED,

    LIST_ENFANTS,
    LIST_ENFANTS_TRANSPORTED,
    LIST_ENFANTS_ON_BOARD,
    LIST_ENFANTS_OFF_BOARD,
    LIST_ENFANTS_ACCEPTED_CANDIDATURES,
    LIST_ENFANTS_WITHOUT_TRAJET,
    LIST_ENFANTS_WITHOUT_BUS,

    FIND_CHAUFFEUR_BY_BUS,
    FIND_BUS_FOR_CHAUFFEUR,

    FIND_ENFANT,
    FIND_TRAJET_FOR_ENFANT,
    FIND_BUS_FOR_ENFANT,
    LIST_ENFANTS_BY_BUS,
    LIST_ENFANTS_BY_TRAJET,

    LIST_MAITRESSES,
    LIST_BUSES,
    LIST_TRAJETS,
    LIST_BUSES_WITHOUT_MAITRESSE,
    LIST_TRAJETS_WITHOUT_BUS,
    LIST_PENDING_ENFANT_CANDIDATURES,
    LIST_PENDING_CHAUFFEUR_CANDIDATURES,
    LIST_PENDING_CANDIDATURES_BOTH,

    FIND_MAITRESSE_BY_BUS,
    FIND_BUS_FOR_MAITRESSE,

    SEARCH_MAITRESSE,
    SEARCH_BUS,

    GENERAL_SCHOOL_INFO,

    GREETING_SMALLTALK,

    OUT_OF_SCOPE_GLOBAL,
    UNSUPPORTED
}
